@CoreBank.Api_HostAddress = https://localhost:7122

# Cole abaixo os tokens atuais antes dos testes.
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWlsdiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Ik1pbGxzYW50QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzkwOTA0OTM3LCJpc3MiOiJDb3JlQmFuay5BcGkiLCJhdWQiOiJDb3JlQmFuay5DbGllbnQifQ.OxjBL_zwHwhuyQGiWMvtcbn2vr6Jb66OhwR_25Cltng
@adminToken = colar_aqui_o_token_do_administrador

### ============================================================
### COREBANK - TESTES FINAIS DO BACKEND
### ============================================================


### ============================================================
### 1. ENDPOINT PROTEGIDO SEM TOKEN
### ============================================================

### Esperado:
### 401 Unauthorized
### Mensagem:
### Você precisa estar autenticado para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me
Accept: application/json

###

### Criar cliente para teste do Login

### Criar cliente exclusivo para teste do Login

POST https://localhost:7122/api/Customers
Content-Type: application/json

{
  "name": "adm CoreBank",
  "cpf": "71992806020",
  "email": "adm@corebank.com",
  "password": "CoreBank@123"
}
### ============================================================
### 2. ENDPOINT COM TOKEN INVÁLIDO
### ============================================================

### Esperado:
### 401 Unauthorized
### Mensagem:
### Você precisa estar autenticado para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me
Accept: application/json
Authorization: Bearer TOKEN_INVALIDO

###


### ============================================================
### 3. CLIENTE TENTANDO ACESSAR ÁREA ADMINISTRATIVA
### ============================================================

### Esperado:
### 403 Forbidden
### Mensagem:
### Você não possui permissão para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Admin/test
Accept: application/json
Authorization: Bearer {{customerToken}}

###


### ============================================================
### 4. ADMIN TENTANDO ACESSAR ÁREA DO CLIENTE
### ============================================================

### Esperado:
### 403 Forbidden
### Mensagem:
### Você não possui permissão para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me
Accept: application/json
Authorization: Bearer {{adminToken}}

###


### ============================================================
### 5. CONSULTAR EXTRATO DA MARIA
### ============================================================

### Esperado:
### 200 OK
###
### Verificar:
### - Saldo correto
### - Status da conta em português
### - Tipos das movimentações em português
### - Datas no formato dd/MM/yyyy HH:mm:ss
### - Horário correto de Brasília

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me/statement
Accept: application/json
Authorization: Bearer {{customerToken}}

###

### ============================================================
### LOGIN - TESTE COREBANK
### ============================================================

POST {{CoreBank.Api_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "Millsant@gmail.com",
  "password": "Milio@123"
}

###

### ============================================================
### CRIAR CONTA - TESTE COREBANK
### ============================================================

POST {{CoreBank.Api_HostAddress}}/api/Accounts
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "agency": "0002",
  "number": "00002"
}

###