@CoreBank.Api_HostAddress = https://localhost:7122

# Cole abaixo os tokens atuais antes dos testes.
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdGUgQ29yZUJhbmsiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0ZUBjb3JlYmFuay5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc5MDgyMTk1OCwiaXNzIjoiQ29yZUJhbmsuQXBpIiwiYXVkIjoiQ29yZUJhbmsuQ2xpZW50In0.V4jKtTG5gU_pqiaQFef93h4dVXZQg3T_o4s8v4hVcnY
@adminToken = colar_aqui_o_token_do_administrador

### ============================================================
### COREBANK - TESTES FINAIS DO BACKEND
### ============================================================


### ============================================================
### 1. ENDPOINT PROTEGIDO SEM TOKEN
### ============================================================

### Esperado:
### 401 Unauthorized
### Mensagem:
### Você precisa estar autenticado para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me
Accept: application/json

###

### Criar cliente para teste do Login

### Criar cliente exclusivo para teste do Login

POST https://localhost:7122/api/Customers
Content-Type: application/json

{
  "name": "adm CoreBank",
  "cpf": "71992806020",
  "email": "adm@corebank.com",
  "password": "CoreBank@123"
}
### ============================================================
### 2. ENDPOINT COM TOKEN INVÁLIDO
### ============================================================

### Esperado:
### 401 Unauthorized
### Mensagem:
### Você precisa estar autenticado para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me
Accept: application/json
Authorization: Bearer TOKEN_INVALIDO

###


### ============================================================
### 3. CLIENTE TENTANDO ACESSAR ÁREA ADMINISTRATIVA
### ============================================================

### Esperado:
### 403 Forbidden
### Mensagem:
### Você não possui permissão para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Admin/test
Accept: application/json
Authorization: Bearer {{customerToken}}

###


### ============================================================
### 4. ADMIN TENTANDO ACESSAR ÁREA DO CLIENTE
### ============================================================

### Esperado:
### 403 Forbidden
### Mensagem:
### Você não possui permissão para acessar este recurso.

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me
Accept: application/json
Authorization: Bearer {{adminToken}}

###


### ============================================================
### 5. CONSULTAR EXTRATO DA MARIA
### ============================================================

### Esperado:
### 200 OK
###
### Verificar:
### - Saldo correto
### - Status da conta em português
### - Tipos das movimentações em português
### - Datas no formato dd/MM/yyyy HH:mm:ss
### - Horário correto de Brasília

GET {{CoreBank.Api_HostAddress}}/api/Accounts/me/statement
Accept: application/json
Authorization: Bearer {{customerToken}}

###

### ============================================================
### LOGIN - TESTE COREBANK
### ============================================================

POST {{CoreBank.Api_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "teste@corebank.com",
  "password": "CoreBank@456"
}

###

### ============================================================
### CRIAR CONTA - TESTE COREBANK
### ============================================================

POST {{CoreBank.Api_HostAddress}}/api/Accounts
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "agency": "0001",
  "number": "00001"
}

###